/**
 * Merges env/env.{APP_ENV}.js + optional env/env.{APP_ENV}.secrets.js
 * into public/env.js as window.ENV for runtime loading from index.html.
 *
 * Usage:
 *   APP_ENV=local node scripts/generate-env.js
 *   npm run env:generate
 */
import { existsSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

const envName = (process.env.APP_ENV || process.env.MODE || 'local').toLowerCase();
const allowed = new Set(['local', 'dev', 'uat', 'stage', 'prod']);
if (!allowed.has(envName)) {
  console.error(`[generate-env] Unknown APP_ENV="${envName}". Use: ${[...allowed].join(', ')}`);
  process.exit(1);
}

const basePath = path.join(root, 'env', `env.${envName}.js`);
const secretsPath = path.join(root, 'env', `env.${envName}.secrets.js`);
const outPath = path.join(root, 'public', 'env.js');

if (!existsSync(basePath)) {
  console.error(`[generate-env] Missing ${basePath}`);
  process.exit(1);
}

const base = (await import(pathToFileURL(basePath).href)).default;
let secrets = {};
if (existsSync(secretsPath)) {
  secrets = (await import(pathToFileURL(secretsPath).href)).default;
  console.log(`[generate-env] Merged secrets from env.${envName}.secrets.js`);
} else {
  console.warn(`[generate-env] No secrets file at env/env.${envName}.secrets.js (using base only)`);
}

const merged = {
  ...base,
  ...secrets,
  APP_ENV: envName,
};

const body = `/* Generated by scripts/generate-env.js — do not edit by hand */\nwindow.ENV = ${JSON.stringify(merged, null, 2)};\n`;
writeFileSync(outPath, body, 'utf8');
console.log(`[generate-env] Wrote ${path.relative(root, outPath)} (APP_ENV=${envName})`);
